# Define a base stage that uses the official python runtime base image
FROM python:3.11-slim AS base

# Add curl for healthcheck + openssl for certificates
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl openssl && \
    rm -rf /var/lib/apt/lists/*

# Set the application directory
WORKDIR /usr/local/app

# Install our requirements.txt
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Generate SSL certificates
RUN mkdir -p /app/certs && \
    openssl req -x509 -newkey rsa:4096 -keyout /app/certs/key.pem -out /app/certs/cert.pem \
    -days 365 -nodes -subj "/C=SN/ST=Dakar/L=Dakar/O=DevOps/OU=IT/CN=localhost" && \
    chmod 644 /app/certs/cert.pem && \
    chmod 600 /app/certs/key.pem

# Define a stage specifically for development, where it'll watch for
# filesystem changes
FROM base AS dev
RUN pip install watchdog
ENV FLASK_ENV=development
CMD ["python", "app.py"]

# Define the final stage that will bundle the application for production
FROM base AS final

# Copy our code from the current folder to the working directory inside the container
COPY . .

# Make port 443 available for HTTPS
EXPOSE 443

# Define our command to be run when launching the container
CMD ["gunicorn", "app:app", "-b", "0.0.0.0:443", "--certfile=/app/certs/cert.pem", "--keyfile=/app/certs/key.pem", "--log-file", "-", "--access-logfile", "-", "--workers", "4", "--keep-alive", "0"]
